=== AlbertoFerrara/TecWeb/cgi-bin/xml/DatabaseCommenti.xsd
<?xml version="1.0" encoding="UTF-8"?>

	<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

	<xsd:element name="commenti" type="TCommenti"/>

	<xsd:complexType name="TCommenti">
	    <xsd:sequence minOccurs="0" maxOccurs="unbounded">
	        <xsd:element name="commento" type="TCommento"/>
	    </xsd:sequence>
	</xsd:complexType>
    	<xsd:complexType name="TCommento">
		  	<xsd:sequence>
	   			<xsd:element name="nome" type="xsd:string"/>
 	   			<xsd:element name="email" type="xsd:string"/>
	   			<xsd:element name="testo" type="xsd:string"/>
					<xsd:element name="dataora" type="xsd:string"/>
					<xsd:element name="id_commento" type="xsd:string"/>
	  		</xsd:sequence>
		</xsd:complexType>
	</xsd:schema>

=== AlbertoFerrara/TecWeb/cgi-bin/xml/DatabaseCommenti.xml
<?xml version="1.0" encoding="UTF-8"?>

<commenti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="./Commenti ./DatabaseCommenti.xsd">
	<commento>
		<nome>Giuseppe</nome>
		<email>giuseppe@gmail.com</email>
		<testo>Bella copisteria complimenti!</testo>
		<dataora>Thu Dec 10 12:12:30 2015</dataora>
		<id_commento>2</id_commento>
	</commento>
	<commento>
		<nome>Antonio</nome>
		<email>beppe@gmail.it</email>
		<testo>Le fotocopie fatte all'istante, e i commessi gentilissimi.</testo>
		<dataora>Thu Nov 24 16:28:30 2015</dataora>
		<id_commento>1</id_commento>
	</commento>
</commenti>
